# ビームの設定をするファイルです。
# 書き方は下記の例に沿って下さい。

# ～パーティクル名について～
# パーティクル名は src/pocketmine/level/particle にあるファイルの名前からParticle.phpを消したものになります。
# 例えば、FlameParticle.php であればパーティクル名は Flame になります。
# ファイルが見れないよって方は https://github.com/pmmp/PocketMine-MP/tree/master/src/pocketmine/level/particle をご覧下さい。
# 何個か使えないものがあります。ごめんなさい。

283:          # ビームを撃つアイテムのID
  - Flame     # パーティクル名
  - 10        # ビームの長さ
  - 5         # 与えるダメージ
  - 0.4       # ノックバックの強さ
  - [15/10/1] # 付与するエフェクトのID/持続時間(秒)/強さ ※必ず[]を書き、複数のエフェクトを付与する場合は , で区切って下さい。何も付与しない場合は [] のみ書いて下さい。
284:
  - Critical
  - 15
  - 7
  - 0.8
  - []
285:
  - Heart
  - 20
  - 0
  - 0
  - [10/30/2, 18/30/2]